### Listar
GET http://127.0.0.1:8000/api/almacen?sucursal=1
Authorization: Bearer 14|zB3loITAdvjMaopRyRE3nryIylmKv90bUasgOrM2a25f615a

### Guardar
POST http://127.0.0.1:8000/api/almacen
Authorization: Bearer 14|zB3loITAdvjMaopRyRE3nryIylmKv90bUasgOrM2a25f615a
Content-Type: application/json
Accept: application/json

{
    "nombre": "CASA MATRIZ",
    "codigo": "ALM-003",
    "descripcion": "Pr Alm",
    "sucursal_id": 2
}

### mostrar un almacen
GET http://127.0.0.1:8000/api/almacen/1
Authorization: Bearer 9|L8DMl3YmLN9OX30NXXyBORz5q0QwKrq0EKLQVaAC329e7b34


