### Lista de productos con paginación
GET http://127.0.0.1:8000/api/producto?page=1&limit=5&search=
Authorization: Bearer 12|Yc3aoQ1xE0nvi3WdJH6qrbQxLUCuEaWj2ATuxBbKcdf7a885
Accept: application/json

### Guardar Producto
POST http://127.0.0.1:8000/api/producto
Authorization: Bearer 6|H2F3SYCcgiP7By6VRjqCiABa5xiXLx28YjsRYb1w458fdbcc
Accept: application/json
Content-Type: application/json

{
    "nombre": "PARLANTE",
    "descripcion": "PARLANTE gammer",
    "unidad_medida": "CAJA",
    "marca": "ASUS",
    "precio_venta": 399.50,
    "estado": true,
    "categoria_id": 1
}
