### Listar
GET http://127.0.0.1:8000/api/sucursal
Authorization: Bearer 14|zB3loITAdvjMaopRyRE3nryIylmKv90bUasgOrM2a25f615a

### Guardar
POST http://127.0.0.1:8000/api/sucursal
Authorization: Bearer 14|zB3loITAdvjMaopRyRE3nryIylmKv90bUasgOrM2a25f615a
Content-Type: application/json

{
    "nombre": "Sucursal 2",
    "direccion": "Av. 10 de Noviembre Z. CBA",
    "telefono": "876453",
    "ciudad": "La Paz"
}