GET http://127.0.0.1:8000/api/usuario
Accept: application/json
Authorization: Bearer 10|P4PMz9CN5lkghm0CFfspcNMuAMfbz1BN6AnCrona19868a5f

### Guardar Usaurio
POST http://127.0.0.1:8000/api/usuario
Content-Type: application/json
Accept: application/json
Authorization: Bearer 10|P4PMz9CN5lkghm0CFfspcNMuAMfbz1BN6AnCrona19868a5f

{
    "name": "admin",
    "email": "admin@mail.com",
    "password": "admin54321"
}

### Mostrar
GET http://127.0.0.1:8000/api/usuario/2

### Modificar
PUT http://127.0.0.1:8000/api/usuario/2
Accept: application/json
Content-Type: application/json

{
  "name": "admin modificado",
  "email": "admin.modificado@mail.com",
  "password": "admin54321"
}

### eliminar
DELETE http://127.0.0.1:8000/api/usuario/1
